# Generated by Django 3.1.4 on 2021-03-17 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import groupchat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('stripe_account_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('payment_method_id', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('profile_picture', models.ImageField(default='defaultprofile.jpg', upload_to=groupchat.models.to_upload_profile_picture)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('P', 'Paypal'), ('S', 'Stripe')], default=None, max_length=1)),
                ('monthly_charge', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.CharField(blank=True, max_length=30)),
                ('plan_id', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('privacy', models.CharField(default='N', max_length=10, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], default='N', max_length=1)),
                ('cycle', models.IntegerField(default=0)),
                ('order', models.CharField(max_length=500, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to='groupchat.profile')),
                ('participants', models.ManyToManyField(related_name='Participants', to='groupchat.Profile')),
                ('to_receive', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groupchat.profile')),
            ],
            options={
                'ordering': ('monthly_charge',),
            },
        ),
        migrations.CreateModel(
            name='PaypalSubscriptionPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groupchat.thread')),
            ],
        ),
        migrations.CreateModel(
            name='PaypalSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=5000)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupchat.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupchat.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PaypalPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groupchat.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
