# Generated by Django 3.0.10 on 2020-11-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='total_buyout',
            field=models.IntegerField(default=0),
        ),
    ]
