# Generated by Django 3.0.10 on 2020-11-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0003_thread_total_buyout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('total_buyout',)},
        ),
    ]
