# Generated by Django 3.0.10 on 2020-12-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0005_remove_chatmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='plan_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='thread',
            name='product_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
