# Generated by Django 3.1.4 on 2020-12-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0006_auto_20201211_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_id',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
