# Generated by Django 3.1.4 on 2020-12-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0007_auto_20201220_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_method_id',
            field=models.CharField(blank=True, default=None, max_length=120),
        ),
    ]
