# Generated by Django 3.1.4 on 2020-12-21 03:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0010_thread_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='stripe_id',
            new_name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_account_id',
            field=models.CharField(default=None, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
