# Generated by Django 3.1.4 on 2020-12-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0011_auto_20201221_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='to_receive',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groupchat.profile'),
        ),
    ]
