# Generated by Django 3.1.4 on 2020-12-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0012_auto_20201223_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(related_name='Participants', to='groupchat.Profile'),
        ),
    ]
