# Generated by Django 3.1.4 on 2020-12-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0013_auto_20201223_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to='groupchat.profile'),
        ),
    ]
